---
replacements:
  # use https://en.wikipedia.org/wiki/IETF_language_tag here!
  en-US: &english
    'U.?K.?': 'United Kingdom'
    'Nat Bk': 'National Bank'
    'Phila\b': 'Philadelphia'
    'Leb\b': 'Lebanon '
    '[Pp]res\.?\b': 'President'
    'Svgs': 'Savings'
    'B[kK]': 'Bank'
    "Int'l": 'International'
    'Tex\b': 'Texas'
    'SF': 'San Francisco '
    "C'wealth": 'Commonwealth'
    'Ft?W(orth)?\b': 'Fort Worth'
    "Lux(emb'?g)?\\b": 'Luxemburg'
    'Caymans': 'Cayman Islands'
    '(Cal.?\b\.?|Calif)': 'California'
    'Col\.?\b': 'Colonel'
    'Mgmnt': 'Management'
    'Inds': 'Industries'
    'Liecht\b': 'Liechtenstein'
    '(W.Germany|W. Ger )': 'West Germany'
    'TX': 'Texas'
    'Neth\b\.?': 'Netherlands '
    'NYC': 'New York City'
    'NY': 'New York'
    'Gen\b\.?': 'General'
    "(Gvmt\\.?|[Gg]ov'?t\\.?( [oO]f)?|\\bgovt)": 'Government'
    "United Kingdomgovt": 'United Kingdom Government'
    'Fla': 'Florida'
    '(Wash\W+ )?D\.?C\b\.?': "Washington, D.C."
    'Mgmt': 'Management'
    'Maj\b\.?': 'Major'
    'Aust(ral\b|\.)': 'Australia'
    'Rev\b\.?': 'Reverend'
    ' r\. ': ' President '
    '\bSen\b\.': 'Senator'
    '\bSheikh?\b': 'Sheikh'
    'So( \.)?Afr\b\.?': 'South Africa'
    'Switz\b': 'Switzerland'
    'Union Bank of Switzerland': 'UBS Switzerland'
    "Harvard Endow(m't Mass)?": 'Harvard Endowment'
    '\ABush Energy\z': 'Bush Energy Texas'
    '\AGeorge W. Bush.+': 'George W. Bush'
    '\AGeorge H\. ?W\. Bush.*': 'George H. W. Bush'
    'JB( & )?Assocs\b\.?': "JB & Associates"
    'Lloyd Bentsen US sen 1971-92': 'Senator Lloyd Bentson Jr.'
    'Mt. Blanc co.': 'Mont Blanc Co.'
    'Sid R. Bass': 'Sid Bass'
    'Sheikh (Isa bin )?Khalifah( of Bahrain)?': 'Sheikh Khalifah'
    'Spectrum(7| Seven) Oil Texas': 'Spectrum 7'
    '\AAjman Arab\z': 'Ajman Arab Bank'
    '\AClark Clifford sec Defense 1968-9\z': 'Clark Clifford'
    '(Dunes hotel & Casino Vegas|Dunes Vegas)': 'Dunes Hotel Las Vegas'
    'Ed(win)? Wilson.*': 'Edwin Wilson'
    '(Evergreen Air|Evergreen International Airlines Marana AZ)': 'Evergreen International Airlines, Marana Arizona'
    'Ferdinand Marcos President. Philippines 1965-86': 'Ferdinand Marcos'
    'Gerry Bull founder chmn': 'Gerry Bull'
    'United KingdomGovernment': 'Government United Kingdom'
    'Houstonian Hotel & Conf\.? (Ctr|Center)': 'Houstonian Hotel & Conference Center'
    'Indian Springs St(ate)? Bank.+\z': 'Indian Spring State Bank'
    'King Fahd.+': 'King Fahd'
    '\ALLoyds\z': 'Lloyds Bank'
    'London Cap(ital)? Securities.*': 'London Capital Securities'
    '\A(Michael|Mike) Hand.*': 'Michael Hand'
    'New UPI( Wash. Dc)?': 'New UPI, Washington D.C.'
    '\ANugan Hand.*': 'Nugan Hand Bank, Sydney'
    'Oelikon': 'Oerlikon'
    'Paul Helliwell.*': 'Paul Helliwell'
    'President\. George Bush': 'George H. W. Bush'
    'Richard Helms.+': 'Richard Helms'
    'Russo .*': 'Russo Co. Houston'
    'Theodore Shackley.*': 'Theodore Shackley'
    'Thomas Clines.*': 'Thomas Clines'
    'Thor Security.*': 'Thor Security'
    'William Colby.*': 'William Colby'
    'World Finan\.': 'World Finance Miami'

    # '': ''
  en-UK: *english

