---
replacements:
  # use https://en.wikipedia.org/wiki/IETF_language_tag here!
  en-US: &english
    'U.?K.?': 'United Kingdom'
    'Nat Bk': 'National Bank'
    'Phila\b': 'Philadelphia'
    'Leb\b': 'Lebanon '
    '[Pp]res\.?\b': 'President'
    'B[kK]': 'Bank'
    "Int'l": 'International'
    'Tex\b': 'Texas'
    'SF': 'San Francisco '
    "C'wealth": 'Commonwealth'
    'Ft?W(orth)?\b': 'Fort Worth'
    'Lux\b': 'Luxemburg'
    "Luxemb'?g ": 'Luxemburg'
    'Caymans': 'Cayman Islands'
    'Cal.?\b': 'California '
    'Col\.?\b': 'Colonel'
    'Mgmnt': 'Management'
    'Inds': 'Industries'
    'Liecht\b': 'Liechtenstein'
    '(W.Germany|W. Ger )': 'West Germany'
    'TX': 'Texas'
    'Neth\b\.?': 'Netherlands '
    'NYC': 'New York City'
    'NY': 'New York'
    'Gen\b\.?': 'General'
    "(Gvmt\\.?|[Gg]ov'?t\\.?( [oO]f)?|\\bgovt)": 'Government'
    "United Kingdomgovt": 'United Kingdom Government'
    'Fla': 'Florida'
    '(Wash\W+ )?D\.?C\b\.?': "Washington, D.C."
    'Mgmt': 'Management'
    'Maj\b\.?': 'Major'
    'Aust(ral\b|\.)': 'Australia'
    'Rev\b\.?': 'Reverend'
    ' r\. ': ' President '
    '\bSen\b\.': 'Senator'
    '\bSheikh?\b': 'Sheikh'
    'So( \.)?Afr\b\.?': 'South Africa'
    'Switz\b': 'Switzerland'
    'Union Bank of Switzerland': 'UBS Switzerland'
    "Harvard Endow(m't Mass)?": 'Harvard Endowment'
    '\ABush Energy\z': 'Bush Energy Texas'
    '\AGeorge W. Bush.+': 'George W. Bush'
    'JB( & )?Assocs\b\.?': "JB & Associates"
    'Lloyd Bentsen US sen 1971-92': 'Senator Lloyd Bentson Jr.'
    'Mt. Blanc co.': 'Mont Blanc Co.'
    'Sid R. Bass': 'Sid Bass'
    'Sheikh (Isa bin )?Khalifah( of Bahrain)?': 'Sheikh Khalifah'
    'Spectrum(7| Seven) Oil Texas': 'Spectrum 7'
  en-UK: *english

