---
assured_types:
  '\Ahttp://www.lombardinetworks.net/lombardi.owl#(Merged)?Institution\z':
    type: Organization
  '\Ahttp://www.lombardinetworks.net/lombardi.owl#Person\z':
    type: Person
  'TNi':
    type: Organization
  'TNp':
    type: Person
