#!/bin/sh
echo Running Git pre-commit Hook

staged_ruby_files=`git diff --staged --name-only | \grep '\.rb$'`

if [ ! -z "$staged_ruby_files" ] ; then
  echo "Ruby files have changed, checking full specs, code conventions and docs"
  rake spec
  rake rubocop $staged_ruby_files || (echo "Please fix the code smells" ; exit 1)
  rake doc:create | grep 'warn' -q || (echo "Warnings in documentation" ; exit 1)
  rake doc:create | grep '100\.00%' -q
  if [ ! $? ] ; then
    echo 'Documentation is not 100% complete. Please run rake doc:create'
    exit 1
  fi
fi


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

